apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-app.fullname" . }}
  labels:
    {{- include "spring-boot-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.app.service.management.port }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "spring-boot-app.selectorLabels" . | nindent 4 }}
